# fly.toml app configuration file generated for nlw-connect-node-server on 2026-04-24T20:13:29Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nlw-connect-node-server'
primary_region = 'gru'

[build]

[deploy]
  release_command = "npm run migrations"

[http_service]
  internal_port = 3333
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024

[[services]]
  http_checks = [
    {
      grace_period = "30s", # Increase this to 30s or 60s
      interval = "10s",
      method = "get",
      path = "/health", # Ensure this route exists and returns 200
      timeout = "2s"
    }
  ]
